all:
	python3 Özdil_Seckin_Abdullah_python.py
	perl Özdil_Seckin_Abdullah_perl_dynamic.pl
	perl Özdil_Seckin_Abdullah_perl_static.pl
	php Özdil_Seckin_Abdullah_php.php
	firefox Özdil_Seckin_Abdullah_javascript.html
